name: Build

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      # choose your default branch
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "src"

      - name: Create builds branch if it doesn't exist
        run: |
          cd $GITHUB_WORKSPACE/src
          git checkout -b builds || true
          git push -u origin builds || true
        continue-on-error: true

      - name: Checkout builds
        uses: actions/checkout@v3
        with:
          ref: "builds"
          path: "builds"
        continue-on-error: true
      
      - name: Create builds directory if checkout failed
        run: |
          if [ ! -d "$GITHUB_WORKSPACE/builds" ]; then
            mkdir -p "$GITHUB_WORKSPACE/builds"
          fi
        
      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create local.properties
        run: |
          cd $GITHUB_WORKSPACE/src
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          cat local.properties

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds || true
          cp build/plugins.json $GITHUB_WORKSPACE/builds || true

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git init || true
          git checkout -b builds || true
          git add .
          git commit -m "Build $GITHUB_SHA" || true
          git remote add origin "https://github.com/$GITHUB_REPOSITORY.git" || true
          git push -f -u origin builds
        continue-on-error: true
